// <auto-generated />
using System;
using FitnessGym.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FitnessGym.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FitnessGym.Domain.Entities.Gyms.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int?>("Level")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<string>("ModelNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)");

                    b.Property<DateOnly>("PurchaseDate")
                        .HasColumnType("date");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("WarrantyExpirationDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("GymId", "Level");

                    b.ToTable("Equipments", (string)null);
                });

            modelBuilder.Entity("FitnessGym.Domain.Entities.Gyms.Floor", b =>
                {
                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("GymId", "Level");

                    b.HasIndex("GymId", "Level")
                        .IsUnique();

                    b.ToTable("Floors", (string)null);
                });

            modelBuilder.Entity("FitnessGym.Domain.Entities.Gyms.Gym", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Gyms", (string)null);
                });

            modelBuilder.Entity("FitnessGym.Domain.Entities.Gyms.GymCheckIn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CheckInTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId");

                    b.ToTable("GymCheckIns", (string)null);
                });

            modelBuilder.Entity("FitnessGym.Domain.Entities.Gyms.MaintenanceHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("MaintenanceHistory", t =>
                        {
                            t.HasCheckConstraint("CK_Maintenance_Interval", "(\"StartDate\" < \"EndDate\")");
                        });
                });

            modelBuilder.Entity("FitnessGym.Domain.Entities.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccesToken")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("EmergencyPhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8e721037-c9fc-4ca0-80da-b414f5b72d36"),
                            AccesToken = "",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a3aa84b6-0253-41b9-a21b-55bbe94aaa18",
                            CreatedOnUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(1990, 5, 20),
                            Email = "manager@gym.director.com",
                            EmailConfirmed = true,
                            FirstName = "Jim",
                            Gender = 0,
                            IsDeleted = false,
                            LastName = "Cool",
                            LockoutEnabled = false,
                            NormalizedUserName = "MANAGER@GYM.DIRECTOR.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFbRbJbmu8nYxvSs23FRda+J00tLZzHNToHhMOvEqYAHhkQu8J2vqQQXRAzcvfnLJA==",
                            PhoneNumberConfirmed = false,
                            ProfilePicture = "/images/avatars/1.png",
                            RefreshToken = "",
                            SecurityStamp = "355a198b-0bb2-4903-9117-5777c05516af",
                            TwoFactorEnabled = false,
                            UserName = "manager@gym.director.com"
                        },
                        new
                        {
                            Id = new Guid("59bdbc09-57b2-426d-aae9-da830e0382a0"),
                            AccesToken = "",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2edfa390-9a8d-4f57-ad63-9852b37e9b94",
                            CreatedOnUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(1995, 8, 15),
                            Email = "trainer@gym.director.com",
                            EmailConfirmed = true,
                            FirstName = "Costel",
                            Gender = 0,
                            IsDeleted = false,
                            LastName = "Bimius",
                            LockoutEnabled = false,
                            NormalizedUserName = "TRAINER@GYM.DIRECTOR.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENZbfEuWWI/RNCj0lA2Q6vgpn27zFjB+qRP8DBW2FxkWsBJL2Zv1vxjalZG750/GmA==",
                            PhoneNumberConfirmed = false,
                            ProfilePicture = "/images/avatars/1.png",
                            RefreshToken = "",
                            SecurityStamp = "28570adb-d461-4a19-8492-7ff3985b1604",
                            TwoFactorEnabled = false,
                            UserName = "trainer@gym.director.com"
                        },
                        new
                        {
                            Id = new Guid("34c33d5b-e131-4724-95ec-d97f0f4a494b"),
                            AccesToken = "",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e6d5ee20-aa82-4677-8117-0889f370dd9d",
                            CreatedOnUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(1993, 2, 10),
                            Email = "technician@gym.director.com",
                            EmailConfirmed = true,
                            FirstName = "John",
                            Gender = 0,
                            IsDeleted = false,
                            LastName = "Geri",
                            LockoutEnabled = false,
                            NormalizedUserName = "TECHNICIAN@GYM.DIRECTOR.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECYxmErMSiKI5VomqsWYXI3WXDY/fVIvXubcURFv7zfmLSQFHnz4mOzqnqdO77aitw==",
                            PhoneNumberConfirmed = false,
                            ProfilePicture = "/images/avatars/1.png",
                            RefreshToken = "",
                            SecurityStamp = "cc10a5c0-5683-4722-ba7d-2611955115ec",
                            TwoFactorEnabled = false,
                            UserName = "technician@gym.director.com"
                        },
                        new
                        {
                            Id = new Guid("8ea4fb46-51bc-415d-9ec0-013683d29411"),
                            AccesToken = "",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d894bce4-3544-430c-8dcc-a19d3c819624",
                            CreatedOnUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(2000, 8, 6),
                            Email = "receptionist@gym.director.com",
                            EmailConfirmed = true,
                            FirstName = "Miriam",
                            Gender = 1,
                            IsDeleted = false,
                            LastName = "Tuiar",
                            LockoutEnabled = false,
                            NormalizedUserName = "RECEPTIONIST@GYM.DIRECTOR.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEM9CeFjYj6oyt1/UWh0OeZ0/GIiUbsVOSz7zryGVnPqHa7kK+dIbvPOdek0hYHw75w==",
                            PhoneNumberConfirmed = false,
                            ProfilePicture = "/images/avatars/1.png",
                            RefreshToken = "",
                            SecurityStamp = "27cb06f0-6ee2-407a-8dc1-537cebe8371d",
                            TwoFactorEnabled = false,
                            UserName = "receptionist@gym.director.com"
                        });
                });

            modelBuilder.Entity("FitnessGym.Domain.Entities.Members.Membership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("QRCode")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("RenewalDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GymId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("MemberId");

                    b.ToTable("Memberships", null, t =>
                        {
                            t.HasCheckConstraint("CK_Expiration_Interval", "(\"RenewalDate\" < \"ExpirationDate\")");
                        });
                });

            modelBuilder.Entity("FitnessGym.Domain.Entities.Members.StaffBooking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RequestStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SessionEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("SessionStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("MemberId");

                    b.HasIndex("StaffId");

                    b.ToTable("StaffBookings", (string)null);
                });

            modelBuilder.Entity("FitnessGym.Domain.Entities.Members.StaffSchedule", b =>
                {
                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("BreakEndTime")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("BreakStartTime")
                        .HasColumnType("interval");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("interval");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("interval");

                    b.HasKey("StaffId", "DayOfWeek");

                    b.HasIndex("StaffId", "DayOfWeek")
                        .IsUnique();

                    b.ToTable("StaffSchedule");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1f1e61a8-b164-43a9-8238-2902727852ce"),
                            Name = "Member",
                            NormalizedName = "MEMBER"
                        },
                        new
                        {
                            Id = new Guid("ff98ec1b-2ffe-4a66-8436-9baa85329f2c"),
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = new Guid("43ec62f7-5aae-4ed8-bfef-c2daa8e2e419"),
                            Name = "Trainer",
                            NormalizedName = "TRAINER"
                        },
                        new
                        {
                            Id = new Guid("adfc9c57-2d88-4abd-9f8e-87774a6eb3fa"),
                            Name = "Technician",
                            NormalizedName = "TECHNICIAN"
                        },
                        new
                        {
                            Id = new Guid("d5afffb8-b3ba-453b-a85d-fe736f59060d"),
                            Name = "Receptionist",
                            NormalizedName = "RECEPTIONIST"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("8e721037-c9fc-4ca0-80da-b414f5b72d36"),
                            RoleId = new Guid("ff98ec1b-2ffe-4a66-8436-9baa85329f2c")
                        },
                        new
                        {
                            UserId = new Guid("59bdbc09-57b2-426d-aae9-da830e0382a0"),
                            RoleId = new Guid("43ec62f7-5aae-4ed8-bfef-c2daa8e2e419")
                        },
                        new
                        {
                            UserId = new Guid("34c33d5b-e131-4724-95ec-d97f0f4a494b"),
                            RoleId = new Guid("43ec62f7-5aae-4ed8-bfef-c2daa8e2e419")
                        },
                        new
                        {
                            UserId = new Guid("8ea4fb46-51bc-415d-9ec0-013683d29411"),
                            RoleId = new Guid("d5afffb8-b3ba-453b-a85d-fe736f59060d")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FitnessGym.Domain.Entities.Gyms.Equipment", b =>
                {
                    b.HasOne("FitnessGym.Domain.Entities.Gyms.Floor", "Floor")
                        .WithMany("Equipments")
                        .HasForeignKey("GymId", "Level");

                    b.OwnsOne("FitnessGym.Domain.Entities.Gyms.FloorLocation", "FloorLocation", b1 =>
                        {
                            b1.Property<Guid>("EquipmentId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<int>("Column")
                                .HasColumnType("integer");

                            b1.Property<int>("Row")
                                .HasColumnType("integer");

                            b1.HasKey("EquipmentId");

                            b1.ToTable("Equipments");

                            b1.WithOwner()
                                .HasForeignKey("EquipmentId");
                        });

                    b.Navigation("Floor");

                    b.Navigation("FloorLocation")
                        .IsRequired();
                });

            modelBuilder.Entity("FitnessGym.Domain.Entities.Gyms.Floor", b =>
                {
                    b.HasOne("FitnessGym.Domain.Entities.Gyms.Gym", "Gym")
                        .WithMany("Floors")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gym");
                });

            modelBuilder.Entity("FitnessGym.Domain.Entities.Gyms.Gym", b =>
                {
                    b.OwnsOne("FitnessGym.Domain.Entities.Gyms.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("GymId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("BuildingNumber")
                                .HasColumnType("text");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("GymId");

                            b1.ToTable("Gyms");

                            b1.WithOwner()
                                .HasForeignKey("GymId");
                        });

                    b.OwnsOne("FitnessGym.Domain.Entities.Gyms.GeoCoordinate", "GeoCoordinate", b1 =>
                        {
                            b1.Property<Guid>("GymId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Latitude")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("Longitude")
                                .HasColumnType("numeric");

                            b1.HasKey("GymId");

                            b1.ToTable("Gyms");

                            b1.WithOwner()
                                .HasForeignKey("GymId");
                        });

                    b.OwnsOne("FitnessGym.Domain.Entities.Gyms.Layout", "Layout", b1 =>
                        {
                            b1.Property<Guid>("GymId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<int>("FloorNumber")
                                .HasColumnType("integer");

                            b1.Property<int>("Length")
                                .HasColumnType("integer");

                            b1.Property<int>("Width")
                                .HasColumnType("integer");

                            b1.HasKey("GymId");

                            b1.ToTable("Gyms");

                            b1.WithOwner()
                                .HasForeignKey("GymId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("GeoCoordinate")
                        .IsRequired();

                    b.Navigation("Layout")
                        .IsRequired();
                });

            modelBuilder.Entity("FitnessGym.Domain.Entities.Gyms.GymCheckIn", b =>
                {
                    b.HasOne("FitnessGym.Domain.Entities.Members.Membership", "Membership")
                        .WithMany("GymCheckIns")
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("FitnessGym.Domain.Entities.Gyms.MaintenanceHistory", b =>
                {
                    b.HasOne("FitnessGym.Domain.Entities.Gyms.Equipment", "Equipment")
                        .WithMany("MaintenanceHistory")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("FitnessGym.Domain.Entities.Members.Membership", b =>
                {
                    b.HasOne("FitnessGym.Domain.Entities.Gyms.Gym", "Gym")
                        .WithMany("Memberships")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessGym.Domain.Entities.Identity.ApplicationUser", "Member")
                        .WithMany("Memberships")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gym");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("FitnessGym.Domain.Entities.Members.StaffBooking", b =>
                {
                    b.HasOne("FitnessGym.Domain.Entities.Identity.ApplicationUser", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessGym.Domain.Entities.Identity.ApplicationUser", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("FitnessGym.Domain.Entities.Members.StaffSchedule", b =>
                {
                    b.HasOne("FitnessGym.Domain.Entities.Identity.ApplicationUser", "Staff")
                        .WithMany("StaffSchedule")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("FitnessGym.Domain.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("FitnessGym.Domain.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessGym.Domain.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("FitnessGym.Domain.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FitnessGym.Domain.Entities.Gyms.Equipment", b =>
                {
                    b.Navigation("MaintenanceHistory");
                });

            modelBuilder.Entity("FitnessGym.Domain.Entities.Gyms.Floor", b =>
                {
                    b.Navigation("Equipments");
                });

            modelBuilder.Entity("FitnessGym.Domain.Entities.Gyms.Gym", b =>
                {
                    b.Navigation("Floors");

                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("FitnessGym.Domain.Entities.Identity.ApplicationUser", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("StaffSchedule");
                });

            modelBuilder.Entity("FitnessGym.Domain.Entities.Members.Membership", b =>
                {
                    b.Navigation("GymCheckIns");
                });
#pragma warning restore 612, 618
        }
    }
}
